[33md516e65[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mdev[m[33m, [m[1;31morigin/dev[m[33m)[m Refined the Alumni dashboard and added some functionalities
client/src/components/dashboard/AlumniDashboardPage.jsx
client/src/components/dashboard/StudentDashboardPage.jsx
client/src/components/messaging/MessageInterface.jsx
client/src/components/profile/ProfileCard.jsx
client/src/pages/AlumniDashboard.jsx
client/src/pages/Dashboard.jsx
client/src/pages/Jobs.jsx
client/src/pages/Profile.jsx
client/src/pages/StudentDashboard.jsx
[33m3bc4a90[m Integrated sign up and sign in with Landing page route
client/src/App.jsx
client/src/components/auth/AuthForm.jsx
client/src/components/auth/AuthModal.jsx
client/src/components/home/Hero.jsx
client/src/components/layout/LandingNavbar.jsx
client/src/components/layout/Navbar.jsx
client/src/index.css
client/src/pages/Index.jsx
client/src/pages/Login.jsx
client/src/pages/Register.jsx
[33m29a9214[m Separated the functionalities for Student and Alumni Dashboards
client/src/App.jsx
client/src/components/auth/AuthForm.jsx
client/src/components/dashboard/AlumniDashboardPage.jsx
client/src/components/dashboard/StudentDashboardPage.jsx
client/src/components/jobs/JobBoard.jsx
client/src/components/layout/Navbar.jsx
client/src/index.css
client/src/pages/AlumniDashboard.jsx
client/src/pages/StudentDashboard.jsx
[33m800100c[m Created Landing page and React components
client/.gitignore
client/README.md
client/bun.lockb
client/components.json
client/eslint.config.js
client/index.html
client/package-lock.json
client/package.json
client/postcss.config.js
client/public/favicon.ico
client/public/placeholder.svg
client/public/robots.txt
client/src/App.css
client/src/App.jsx
client/src/components/auth/AuthForm.jsx
client/src/components/dashboard/AlumniDashboardPage.jsx
client/src/components/dashboard/DashboardPage.jsx
client/src/components/dashboard/StudentDashboardPage.jsx
client/src/components/home/Hero.jsx
client/src/components/jobs/JobBoard.jsx
client/src/components/layout/Navbar.jsx
client/src/components/messaging/MessageInterface.jsx
client/src/components/profile/ProfileCard.jsx
client/src/components/ui/accordion.jsx
client/src/components/ui/alert-dialog.jsx
client/src/components/ui/alert.jsx
client/src/components/ui/aspect-ratio.jsx
client/src/components/ui/avatar.jsx
client/src/components/ui/badge.jsx
client/src/components/ui/breadcrumb.jsx
client/src/components/ui/button.jsx
client/src/components/ui/calendar.jsx
client/src/components/ui/card.jsx
client/src/components/ui/carousel.jsx
client/src/components/ui/chart.jsx
client/src/components/ui/checkbox.jsx
client/src/components/ui/collapsible.jsx
client/src/components/ui/command.jsx
client/src/components/ui/context-menu.jsx
client/src/components/ui/dialog.jsx
client/src/components/ui/drawer.jsx
client/src/components/ui/dropdown-menu.jsx
client/src/components/ui/form.jsx
client/src/components/ui/hover-card.jsx
client/src/components/ui/input-otp.jsx
client/src/components/ui/input.jsx
client/src/components/ui/label.jsx
client/src/components/ui/menubar.jsx
client/src/components/ui/navigation-menu.jsx
client/src/components/ui/pagination.jsx
client/src/components/ui/popover.jsx
client/src/components/ui/progress.jsx
client/src/components/ui/radio-group.jsx
client/src/components/ui/resizable.jsx
client/src/components/ui/scroll-area.jsx
client/src/components/ui/select.jsx
client/src/components/ui/separator.jsx
client/src/components/ui/sheet.jsx
client/src/components/ui/sidebar.jsx
client/src/components/ui/skeleton.jsx
client/src/components/ui/slider.jsx
client/src/components/ui/sonner.jsx
client/src/components/ui/switch.jsx
client/src/components/ui/table.jsx
client/src/components/ui/tabs.jsx
client/src/components/ui/textarea.jsx
client/src/components/ui/toast.jsx
client/src/components/ui/toaster.jsx
client/src/components/ui/toggle-group.jsx
client/src/components/ui/toggle.jsx
client/src/components/ui/tooltip.jsx
client/src/components/ui/use-toast.js
client/src/hooks/use-mobile.jsx
client/src/hooks/use-toast.js
client/src/index.css
client/src/lib/utils.js
client/src/main.jsx
client/src/pages/AlumniDashboard.jsx
client/src/pages/Dashboard.jsx
client/src/pages/Index.jsx
client/src/pages/Jobs.jsx
client/src/pages/Login.jsx
client/src/pages/Messages.jsx
client/src/pages/NotFound.jsx
client/src/pages/Profile.jsx
client/src/pages/Register.jsx
client/src/pages/StudentDashboard.jsx
client/src/vite-env.d.ts
client/tailwind.config.js
client/tsconfig.app.json
client/tsconfig.json
client/tsconfig.node.json
client/vite.config.js
[33m4502827[m Moved backend files into server directory
server/.gitignore
server/Config/db.js
server/Config/package-lock.json
server/Config/package.json
server/Controllers/alumniController.js
server/Controllers/authController.js
server/Controllers/jobPostingController.js
server/Controllers/mentorshipController.js
server/Controllers/mentorshipFeedbackController.js
server/Controllers/mentorshipSessionController.js
server/Controllers/messageController.js
server/Controllers/notificationController.js
server/Controllers/studentController.js
server/Models/Alumni.js
server/Models/JobPosting.js
server/Models/Mentorship.js
server/Models/MentorshipFeedback.js
server/Models/MentorshipSession.js
server/Models/Message.js
server/Models/Notification.js
server/Models/Student.js
server/Models/index.js
server/Models/package-lock.json
server/Models/package.json
server/README.md
server/Routes/alumniRoutes.js
server/Routes/authRoutes.js
server/Routes/jobPostingRoutes.js
server/Routes/mentorshipRoutes.js
server/Routes/messageRoutes.js
server/Routes/notificationRoutes.js
server/Routes/studentRoutes.js
server/Sample_Data/alumni.json
server/Sample_Data/discussions.json
server/Sample_Data/events.json
server/Sample_Data/mentorship_requests.json
server/Sample_Data/student.json
server/Utils/emailService.js
server/Utils/fileUpload.js
server/Utils/generateToken.js
server/Utils/responseFormatter.js
server/Utils/tokenGenerator.js
server/adds.js
server/gitignore
server/middleware/authMiddleware.js
server/middleware/errorMiddleware.js
server/middleware/rateLimitMiddleware.js
server/package-lock.json
server/package.json
server/server.js
